#!/bin/bash

TEMP="/tmp/src.txt"
DOWNLOAD="index.html?country=BR&protocol=http&protocol=https&ip_version=4" 
URL="https://www.archlinux.org/mirrorlist/?country=BR&protocol=http&protocol=https&ip_version=4" 
DEST="/etc/pacman.d/mirrorlist"

if wget -q "$URL"; then
  [ -e "$TEMP" ] && rm "$TEMP"
  sed -i 's/#//' "$DOWNLOAD"
  rankmirrors -n 0 "$DOWNLOAD" > "$TEMP" 
  rm "$DOWNLOAD"
  echo "$(tail -n +7 "$TEMP")" > $TEMP

  echo -e "#------------------------------------#
#  Feito por:                        #
#------------------------------------#
#   __     ___      _                #
#   \ \   / (_) ___| |_ ___  _ __    #
#    \ \ / /| |/ __| __/ _ \| '__|   #
#     \ V / | | (__| || (_) | |      #
#      \_/  |_|\___|\__\___/|_|      #
#------------------------------------#
# Atualizado dia $(date +'%d/%m/%Y %H:%M:%S') #
#------------------------------------#\n" > "$DEST"

  cat "$TEMP" >> "$DEST"

else
  wget --version > /dev/null && echo -e "Falhou!\nVc ta sem net ne mano, como q tu quer roda isso!" && exit 1 || echo "Opa vc nao tem wget, vou instalar p vc" && pacman -S wget && echo "Roda dnv o programinha chefia"
 
fi

exit 0
