#!/bin/bash

intern=eDP
extern=HDMI-A-0

xrandr | grep "$extern disconnected" && xrandr --output "$extern" --off --output "$intern" --auto || xrandr --output "$intern" --off --output "$extern" --auto

exit

